DROP TABLE IF EXISTS logs_death;
CREATE TABLE `logs_death` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`playerId` INT(10) NULL DEFAULT NULL,
	`killerId` INT(10) NULL DEFAULT NULL,
	`weaponId` INT(10) NULL,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;


